[pytest]
filterwarnings =
    ignore:X does not have valid feature names:UserWarning
    ignore:SelectableGroups dict interface is deprecated:DeprecationWarning
    ignore:The set_(bad|over|under) function will be deprecated:PendingDeprecationWarning
