[dataset]
handle = "ealtman2019/ibm-transactions-for-anti-money-laundering-aml"
prefix = "HI-Large"

[split]
test_size = 0.4
random_state = 42

[models.MEGA_PNA]
hidden_channels = 128
num_layers = 2
learning_rate = 0.001
epochs = 80
batch_size = 8192
loss_type = "weighted"
pos_weight = 5.0
dropout = 0.3
final_dropout = 0.3
num_neighbors = [20, 10]
